name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
      strategy:
        matrix:
          node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clean npm cache
      run: npm cache clean --force
    - run: npm ci
    - name: Pull Docker image
      run: sudo docker pull maaz64/payment-service-backend:latest
    - name: Delete Old docker container
      run: sudo docker rm -f payment-service-backend-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name payment-service-backend-container maaz64/payment-service-backend